### ISSUE TITLE
Support Common media_type

### ISSUE THREAD

**Issue by Kl0ven** [wharton/drf-excel#60]
The default common media_type for xlsx `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` 
Is it possible to support this media_type. Maybe in configuration or via a classmethod.

For now I resorted to use :

```python
from django.apps import AppConfig
from drf_excel.renderers import XLSXRenderer

class AppConfig(AppConfig):
    name = "app.app"
    verbose_name = _("app")

def ready(self):
        XLSXRenderer.media_type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
```

**Comment by willtho89** [comment]
You are correct. I made a PR #62 to fix this. I'm not sure if the old media_type was chosen deliberately
