### ISSUE TITLE
Should XLSXListField Support Nullable Values?

### ISSUE THREAD

**Issue by thomasmatecki** [wharton/drf-excel#61]
Currently `XLSXListField` does not behave very nicely if _prepping_ a value of `None`. This field corresponds to DRF's `ListField`, which [does support ](https://github.com/encode/django-rest-framework/issues/5951#issuecomment-383285617) `allow_null=True`.

```
    def prep_value(self) -> Any:
>       if len(self.value) > 0 and isinstance(self.value[0], Iterable):
E       TypeError: object of type 'NoneType' has no len()
```

It seems as though this field should nicely handle null (`None`) values. Happy to open a PR if folks agree.

**Comment by browniebroke** [comment]
Fixed in #78
