### ISSUE TITLE
Example color field is not valid - should be row_color

### ISSUE THREAD

**Issue by nerjan** [wharton/drf-excel#69]
```
class ExampleSerializer(serializers.Serializer):
    color = serializers.SerializerMethodField()

    def get_color(self, instance):
        color_map = {'w': 'FFFFFFCC', 'a': 'FFFFCCCC'}
        return color_map.get(instance.alarm_level, 'FFFFFFFF')
```

This class from example should have "color" changed to "row_color", as described here https://stackoverflow.com/questions/57709727/drf-formatting-xlsx-content

**Comment by FlipperPA** [comment]
I've updated this in the [Configuring Styles](https://github.com/wharton/drf-excel/blob/main/README.md#configuring-styles) section. Thanks for the catch, @nerjan!
