### ISSUE TITLE
Could not satisfy the request Accept header

### ISSUE THREAD

**Issue by HodaSadatJafari** [wharton/drf-excel#80]
I get the following error when I use this package:
{
  "detail": "Could not satisfy the request Accept header."
}

**Comment by rptmat57** [comment]
Hi @HodaSadatJafari ,
Which version of django/drf are you using?

Do you have a test case to reproduce the issue by any chance?

**Comment by HodaSadatJafari** [comment]
djangorestframework==3.14.0
Django==4.2.4

Can this package handle nested serializer?
I think I get this error or this error "Object of type QuerySet is not JSON serializable" when I have nested serializer.
Like this example:
![image](https://github.com/wharton/drf-excel/assets/13479916/ab35524e-b4c7-4c65-ae83-fb854c194f84)

**Comment by rptmat57** [comment]
I just ran a test with the same versions and a `SerializerMethodField` and it worked just fine.

I think your error might be triggered by something else.

**Comment by FlipperPA** [comment]
@HodaSadatJafari Have a look at this: https://stackoverflow.com/questions/30903951/django-doesnt-parse-a-custom-http-accept-header

What is making the request to the endpoint? It sounds like it is sending something non-standard.

**Comment by FlipperPA** [comment]
Closing, no response.
